add esp32c3 example
sajattack/st7735-lcd-examples pull request #5
Opened 2023-07-14 09:46 UTC by kons-9

Hi! I made esp32c3 example!

2023-07-14 19:29 UTC, sajattack commented on README.md
> +| ST7735R Pin | Raspberry Pi Pico Pin |
you forgot to update the name here

2023-07-14 19:31 UTC, sajattack commented on esp32c3-examples/examples/draw_ferris.rs
> +    let hertz = Hertz(30_000_000);
this might be a bit clearer if you use MegaHertz(30)

2023-07-14 19:32 UTC, sajattack requested changes
as above

2023-07-17 04:10 UTC, kons-9 commented
Thank you for reviewing!
I fixed them.

2023-07-17 08:52 UTC, sajattack approved these changes

2023-07-17 08:53 UTC, sajattack commented
Thanks for contributing!

2023-07-17 08:53 UTC, merged